export enum GamemodeEnum {
  osu = 0,
  taiko = 1,
  fruits = 2,
  mania = 3,
};


export enum Genres_enum {
  'Unspecified',
  'Video Game',
  'Anime',
  'Rock',
  'Pop',
  'Other',
  'Novelty',
  'Hip Hop',
  'Electronic',
  'Metal',
  'Classical',
  'Folk',
  'Jazz'
};


export enum Languages_enum {
  Any,
  English,
  Chinese,
  French,
  German,
  Italian,
  Japanese,
  Korean,
  Spanish,
  Swedish,
  Russian,
  Polish,
  Instrumental,
  Unspecified,
  Other,
};


export const ModsCodes: {
  [key: string]: string;
} = {
  1: 'NF',
  2: 'EZ',
  4: 'TD',
  8: 'HD',
  16: 'HR',
  32: 'SD',
  64: 'DT',
  128: 'RX',
  256: 'HT',
  576: 'NC',
  1024: 'FL',
  2048: 'AT',
  4096: 'SO',
  8192: 'AP',
  16416: 'PF',
  32768: '4K',
  65536: '5K',
  131072: '6K',
  262144: '7K',
  524288: '8K',
  1048576: 'FI',
  2097152: 'RD',
  4194304: 'LM',
  8388608: 'Target',
  16777216: '9K',
  33554432: 'KeyCoop',
  67108864: '1K',
  134217728: '3K',
  268435456: '2K',
  536870912: 'ScoreV2',
  1073741824: 'MR',
};

export enum ModsEnum {
  'NF' = 1,
  'EZ' = 2,
  'TD' = 4,
  'HD' = 8,
  'HR' = 16,
  'SD' = 32,
  'DT' = 64,
  'RX' = 128,
  'HT' = 256,
  'NC' = 576,
  'FL' = 1024,
  'AT' = 2048,
  'SO' = 4096,
  'AP' = 8192,
  'PF' = 16416,
  '4K' = 32768,
  '5K' = 65536,
  '6K' = 131072,
  '7K' = 262144,
  '8K' = 524288,
  'FI' = 1048576,
  'RD' = 2097152,
  'LM' = 4194304,
  'Target' = 8388608,
  '9K' = 16777216,
  'KeyCoop' = 33554432,
  '1K' = 67108864,
  '3K' = 134217728,
  '2K' = 268435456,
  'ScoreV2' = 536870912,
  'MR' = 1073741824,
};


export enum ModsEnumBitwise {
  Nomod = 0,
  NoFail = 1 << 0,
  Easy = 1 << 1,
  TouchDevice = 1 << 2,
  Hidden = 1 << 3,
  HardRock = 1 << 4,
  SuddenDeath = 1 << 5,
  DoubleTime = 1 << 6,
  Relax = 1 << 7,
  HalfTime = 1 << 8,
  Nightcore = 1 << 9,
  Flashlight = 1 << 10,
  Autoplay = 1 << 11,
  SpunOut = 1 << 12,
  Relax2 = 1 << 13,
  Perfect = 1 << 14,
  Key4 = 1 << 15,
  Key5 = 1 << 16,
  Key6 = 1 << 17,
  Key7 = 1 << 18,
  Key8 = 1 << 19,
  FadeIn = 1 << 20,
  Random = 1 << 21,
  Cinema = 1 << 22,
  Target = 1 << 23,
  Key9 = 1 << 24,
  Key10 = 1 << 25,
  Key1 = 1 << 26,
  Key3 = 1 << 27,
  Key2 = 1 << 28,
  LastMod = 1 << 29,
  keyMod = Key1 | Key2 | Key3 | Key4 | Key5 | Key6 | Key7 | Key8 | Key9 | Key10,
  KeyModUnranked = Key1 | Key2 | Key3 | Key9 | Key10,
  FreeModAllowed = NoFail | Easy | Hidden | HardRock | SuddenDeath | Flashlight | FadeIn | Relax | Relax2 | SpunOut | keyMod,
  ScoreIncreaseMods = Hidden | HardRock | DoubleTime | Flashlight | FadeIn
};


export const ModsOrder: {
  [key: string]: number;
} = {
  nf: 0,
  ez: 1,
  hd: 2,
  dt: 3,
  nc: 3,
  ht: 3,
  hr: 4,
  so: 5,
  sd: 5,
  pf: 5,
  fl: 6,
  td: 7,
};


export const CountryNames = {
  US: "United States",
  RU: "Russian Federation",
  DE: "Germany",
  PL: "Poland",
  FR: "France",
  JP: "Japan",
  CA: "Canada",
  BR: "Brazil",
  GB: "United Kingdom",
  TW: "Taiwan",
  KR: "South Korea",
  CN: "China",
  AU: "Australia",
  ID: "Indonesia",
  UA: "Ukraine",
  PH: "Philippines",
  CL: "Chile",
  FI: "Finland",
  AR: "Argentina",
  NL: "Netherlands",
  SE: "Sweden",
  SG: "Singapore",
  MX: "Mexico",
  MY: "Malaysia",
  ES: "Spain",
  IT: "Italy",
  HK: "Hong Kong",
  TH: "Thailand",
  VN: "Vietnam",
  NO: "Norway",
  CZ: "Czech Republic",
  TR: "Turkey",
  BY: "Belarus",
  AT: "Austria",
  BE: "Belgium",
  PT: "Portugal",
  RO: "Romania",
  HU: "Hungary",
  DK: "Denmark",
  LT: "Lithuania",
  KZ: "Kazakhstan",
  NZ: "New Zealand",
  PE: "Peru",
  CH: "Switzerland",
  CO: "Colombia",
  IL: "Israel",
  EE: "Estonia",
  BG: "Bulgaria",
  SK: "Slovakia",
  GR: "Greece",
  LV: "Latvia",
  VE: "Venezuela",
  RS: "Serbia",
  IE: "Ireland",
  HR: "Croatia",
  SA: "Saudi Arabia",
  UY: "Uruguay",
  ZA: "South Africa",
  AE: "United Arab Emirates",
  SI: "Slovenia",
  IN: "India",
  EC: "Ecuador",
  MA: "Morocco",
  CR: "Costa Rica",
  MD: "Moldova",
  DO: "Dominican Republic",
  BN: "Brunei",
  EG: "Egypt",
  RE: "Reunion",
  MO: "Macau",
  TN: "Tunisia",
  PA: "Panama",
  DZ: "Algeria",
  MN: "Mongolia",
  PY: "Paraguay",
  KW: "Kuwait",
  PR: "Puerto Rico",
  GE: "Georgia",
  BO: "Bolivia",
  SV: "El Salvador",
  QA: "Qatar",
  GT: "Guatemala",
  LU: "Luxembourg",
  UZ: "Uzbekistan",
  KG: "Kyrgyzstan",
  MK: "North Macedonia",
  KH: "Cambodia",
  BA: "Bosnia and Herzegovina",
  IS: "Iceland",
  JO: "Jordan",
  PK: "Pakistan",
  TT: "Trinidad and Tobago",
  CY: "Cyprus",
  HN: "Honduras",
  NI: "Nicaragua",
  BH: "Bahrain",
  MV: "Maldives",
  BD: "Bangladesh",
  PF: "French Polynesia",
  LB: "Lebanon",
  NP: "Nepal",
  IQ: "Iraq",
  GU: "Guam",
  AZ: "Azerbaijan",
  AL: "Albania",
  MT: "Malta",
  MM: "Myanmar",
  NC: "New Caledonia",
  OM: "Oman",
  IR: "Iran, Islamic Republic of",
  AM: "Armenia",
  GP: "Guadeloupe",
  MQ: "Martinique",
  JM: "Jamaica",
  LA: "Lao People&#039;s Democratic Republic",
  LK: "Sri Lanka",
  PS: "Palestinian Territory Occupied",
  MU: "Mauritius",
  SY: "Syrian Arab Republic",
  ME: "Montenegro",
  FO: "Faroe Islands",
  JE: "Jersey",
  GF: "French Guiana",
  MP: "Northern Mariana Islands",
  IM: "Isle of Man",
  SR: "Suriname",
  BZ: "Belize",
  BB: "Barbados",
  AW: "Aruba",
  LY: "Libya",
  AX: "Aland Islands",
  GG: "Guernsey",
  MG: "Madagascar",
  SD: "Sudan",
  LI: "Liechtenstein",
  BS: "Bahamas",
  KE: "Kenya",
  GL: "Greenland",
  BM: "Bermuda",
  EU: "Europe",
  CI: "Cote D&#039;Ivoire",
  GY: "Guyana",
  GI: "Gibraltar",
  VI: "Virgin Islands, U.S.",
  AD: "Andorra",
  LC: "Saint Lucia",
  TJ: "Tajikistan",
  AG: "Antigua and Barbuda",
  SN: "Senegal",
  PM: "Saint Pierre and Miquelon",
  CK: "Cook Islands",
  AQ: "Antarctica",
  CF: "Central African Republic",
  LR: "Liberia",
  ER: "Eritrea",
};

export const CountryCodes = {
  "United States": 'US',
  "Russian Federation": 'RU',
  "Germany": 'DE',
  "Poland": 'PL',
  "France": 'FR',
  "Japan": 'JP',
  "Canada": 'CA',
  "Brazil": 'BR',
  "United Kingdom": 'GB',
  "Taiwan": 'TW',
  "South Korea": 'KR',
  "China": 'CN',
  "Australia": 'AU',
  "Indonesia": 'ID',
  "Ukraine": 'UA',
  "Philippines": 'PH',
  "Chile": 'CL',
  "Finland": 'FI',
  "Argentina": 'AR',
  "Netherlands": 'NL',
  "Sweden": 'SE',
  "Singapore": 'SG',
  "Mexico": 'MX',
  "Malaysia": 'MY',
  "Spain": 'ES',
  "Italy": 'IT',
  "Hong Kong": 'HK',
  "Thailand": 'TH',
  "Vietnam": 'VN',
  "Norway": 'NO',
  "Czech Republic": 'CZ',
  "Turkey": 'TR',
  "Belarus": 'BY',
  "Austria": 'AT',
  "Belgium": 'BE',
  "Portugal": 'PT',
  "Romania": 'RO',
  "Hungary": 'HU',
  "Denmark": 'DK',
  "Lithuania": 'LT',
  "Kazakhstan": 'KZ',
  "New Zealand": 'NZ',
  "Peru": 'PE',
  "Switzerland": 'CH',
  "Colombia": 'CO',
  "Israel": 'IL',
  "Estonia": 'EE',
  "Bulgaria": 'BG',
  "Slovakia": 'SK',
  "Greece": 'GR',
  "Latvia": 'LV',
  "Venezuela": 'VE',
  "Serbia": 'RS',
  "Ireland": 'IE',
  "Croatia": 'HR',
  "Saudi Arabia": 'SA',
  "Uruguay": 'UY',
  "South Africa": 'ZA',
  "United Arab Emirates": 'AE',
  "Slovenia": 'SI',
  "India": 'IN',
  "Ecuador": 'EC',
  "Morocco": 'MA',
  "Costa Rica": 'CR',
  "Moldova": 'MD',
  "Dominican Republic": 'DO',
  "Brunei": 'BN',
  "Egypt": 'EG',
  "Reunion": 'RE',
  "Macau": 'MO',
  "Tunisia": 'TN',
  "Panama": 'PA',
  "Algeria": 'DZ',
  "Mongolia": 'MN',
  "Paraguay": 'PY',
  "Kuwait": 'KW',
  "Puerto Rico": 'PR',
  "Georgia": 'GE',
  "Bolivia": 'BO',
  "El Salvador": 'SV',
  "Qatar": 'QA',
  "Guatemala": 'GT',
  "Luxembourg": 'LU',
  "Uzbekistan": 'UZ',
  "Kyrgyzstan": 'KG',
  "North Macedonia": 'MK',
  "Cambodia": 'KH',
  "Bosnia and Herzegovina": 'BA',
  "Iceland": 'IS',
  "Jordan": 'JO',
  "Pakistan": 'PK',
  "Trinidad and Tobago": 'TT',
  "Cyprus": 'CY',
  "Honduras": 'HN',
  "Nicaragua": 'NI',
  "Bahrain": 'BH',
  "Maldives": 'MV',
  "Bangladesh": 'BD',
  "French Polynesia": 'PF',
  "Lebanon": 'LB',
  "Nepal": 'NP',
  "Iraq": 'IQ',
  "Guam": 'GU',
  "Azerbaijan": 'AZ',
  "Albania": 'AL',
  "Malta": 'MT',
  "Myanmar": 'MM',
  "New Caledonia": 'NC',
  "Oman": 'OM',
  "Iran, Islamic Republic of": 'IR',
  "Armenia": 'AM',
  "Guadeloupe": 'GP',
  "Martinique": 'MQ',
  "Jamaica": 'JM',
  "Lao People&#039;s Democratic Republic": 'LA',
  "Sri Lanka": 'LK',
  "Palestinian Territory Occupied": 'PS',
  "Mauritius": 'MU',
  "Syrian Arab Republic": 'SY',
  "Montenegro": 'ME',
  "Faroe Islands": 'FO',
  "Jersey": 'JE',
  "French Guiana": 'GF',
  "Northern Mariana Islands": 'MP',
  "Isle of Man": 'IM',
  "Suriname": 'SR',
  "Belize": 'BZ',
  "Barbados": 'BB',
  "Aruba": 'AW',
  "Libya": 'LY',
  "Aland Islands": 'AX',
  "Guernsey": 'GG',
  "Madagascar": 'MG',
  "Sudan": 'SD',
  "Liechtenstein": 'LI',
  "Bahamas": 'BS',
  "Kenya": 'KE',
  "Greenland": 'GL',
  "Bermuda": 'BM',
  "Europe": 'EU',
  "Cote D &#039; Ivoire": 'CI',
  "Guyana": 'GY',
  "Gibraltar": 'GI',
  "Virgin Islands, U.S.": 'VI',
  "Andorra": 'AD',
  "Saint Lucia": 'LC',
  "Tajikistan": 'TJ',
  "Antigua and Barbuda": 'AG',
  "Senegal": 'SN',
  "Saint Pierre and Miquelon": 'PM',
  "Cook Islands": 'CK',
  "Antarctica": 'AQ',
  "Central African Republic": 'CF',
  "Liberia": 'LR',
  "Eritrea": 'ER',
};